const GHIGLIOTTINE = [
  {id:1,w:"RITO",d:1,b:3,s:"CIVILE",c:[{r:"PASSAGGIO",x:"LIVELLO"},{r:"AMBROSIANO",x:"MILANO"},{r:"CAFFÈ",x:"PAUSA"},{r:"CELEBRARE",x:"FESTA"},{r:"INIZIAZIONE",x:"TRIBÙ"}]},
  {id:2,w:"RISONANZA",d:1,b:2,s:"CORPO",c:[{r:"MAGNETICA",x:"ELETTRICA"},{r:"CASSA",x:"RISPARMIO"},{r:"SIMPATIA",x:"PRESSIONE"},{r:"MEDIA",x:"SOCIAL"},{r:"VOCALICA",x:"MUSICALE"}]},
  {id:3,w:"GESTIONE",d:1,b:1,s:"COMMISSARIALE",c:[{r:"PATRIMONIO",x:"EREDITÀ"},{r:"COSTI",x:"RICAVI"},{r:"CALORE",x:"ENERGIA"},{r:"ERRORI",x:"SISTEMA"},{r:"AUTONOMIA",x:"INDIPENDENZA"}]},
  {id:4,w:"PONTE",d:1,b:4,s:"MESSINA",c:[{r:"COMANDO",x:"CONTROLLO"},{r:"DENTI",x:"SORRISO"},{r:"SOSPESO",x:"GIUDIZIO"},{r:"ORO",x:"CORSA"},{r:"PRIMO MAGGIO",x:"CONCERTO"}]},
  {id:5,w:"FANTASIA",d:1,b:4,s:"FINALE",c:[{r:"VOLO",x:"AEREO"},{r:"MAGLIA",x:"LANA"},{r:"WALT DISNEY",x:"FUMETTI"},{r:"GALOPPO",x:"CORSA"},{r:"POTERE",x:"FORZA"}]},
  {id:6,w:"OLTRE",d:1,b:0,s:"GUARDARE",c:[{r:"LIMITE",x:"IGNOTO"},{r:"MURO",x:"CREPA"},{r:"SPERANZA",x:"DELUSIONE"},{r:"BAGLIONI",x:"BATTISTI"},{r:"MODO",x:"MODA"}]},
  {id:7,w:"SPIGA",d:1,b:1,s:"ABBONDANZA",c:[{r:"CAMPO",x:"SETTORE"},{r:"PUNTO",x:"LINEA"},{r:"ORO",x:"FERRO"},{r:"VIA",x:"STRADA"},{r:"CHICCO",x:"CAFFÈ"}]},
  {id:8,w:"GIOSTRA",d:1,b:3,s:"GIRO",c:[{r:"CAVALLI",x:"CORSA"},{r:"TORNEO",x:"DUELLO"},{r:"CALCI",x:"PUGNI"},{r:"COPPA",x:"VINCITORE"},{r:"FERMA",x:"BLOCCATA"}]},
  {id:9,w:"FORO",d:1,b:2,s:"ROMANO",c:[{r:"ELETTRONICO",x:"DIGITALE"},{r:"COMPETENTE",x:"CAPACE"},{r:"PUNTURA",x:"APE"},{r:"PASSANTE",x:"STRADALE"},{r:"FINESTRA",x:"VETRO"}]},
  {id:10,w:"LUCE",d:1,b:0,s:"IN FONDO",c:[{r:"ANNI",x:"SECOLI"},{r:"GAS",x:"PETROLIO"},{r:"DARE",x:"AVERE"},{r:"PUNTI",x:"VITTORIA"},{r:"SPETTRO",x:"FANTASMA"}]},
  {id:11,w:"LISTA",d:1,b:3,s:"NOZZE",c:[{r:"SPESA",x:"CARRELLO"},{r:"ATTESA",x:"PAZIENZA"},{r:"COLPO",x:"STATO"},{r:"SBARCO",x:"NAVE"},{r:"CIVICA",x:"COMUNE"}]},
  {id:12,w:"CAPITOLO",d:1,b:2,s:"CHIUSO",c:[{r:"SPESA",x:"CARRELLO"},{r:"SOSPESO",x:"GIUDIZIO"},{r:"LIBRO",x:"PAGINA"},{r:"STORIA",x:"GEOGRAFIA"},{r:"CATTEDRALE",x:"CHIESA"}]},
  {id:13,w:"BOZZA",d:1,b:1,s:"VENTO",c:[{r:"STAMPA",x:"LIBRO"},{r:"CORREZIONE",x:"MATITA"},{r:"ACCORDO",x:"PACE"},{r:"AUTORE",x:"SCRITTORE"},{r:"FISCALE",x:"TASSE"}]},
  {id:14,w:"METRO",d:1,b:4,s:"NASTRO",c:[{r:"QUADRO",x:"DIPINTO"},{r:"SARTO",x:"AGO"},{r:"FERMATA",x:"AUTOBUS"},{r:"GIUDIZIO",x:"PARERE"},{r:"POESIA",x:"VERSO"}]},
  {id:15,w:"RITMO",d:1,b:4,s:"CIRCADIANO",c:[{r:"SCANDIRE",x:"LEGGERE"},{r:"SOSTENUTO",x:"VELOCE"},{r:"BATTERIA",x:"PENTOLA"},{r:"PERDERE",x:"BUSSOLA"},{r:"LAVORO",x:"FATICA"}]},
  {id:16,w:"NUCLEO",d:1,b:2,s:"FAMILIARE",c:[{r:"CENTRALE",x:"STAZIONE"},{r:"MATERIALE",x:"CANTIERE"},{r:"FONDAMENTALE",x:"IMPORTANTE"},{r:"TERRA",x:"CIELO"},{r:"DURO",x:"LAVORO"}]},
  {id:17,w:"DAMA",d:1,b:1,s:"CINESE",c:[{r:"COMPAGNIA",x:"AMICI"},{r:"PEDINA",x:"SCACCHI"},{r:"BIANCA",x:"NEVE"},{r:"CAVALIERE",x:"CASTELLO"},{r:"PRIMA",x:"SECONDA"}]},
  {id:18,w:"MINIERA",d:1,b:3,s:"ORO",c:[{r:"INFORMAZIONI",x:"SEGRETE"},{r:"CARBONE",x:"FUOCO"},{r:"DATI",x:"RETE"},{r:"CAMPO",x:"FIORI"},{r:"VAGONE",x:"TRENO"}]},
  {id:19,w:"MANIA",d:1,b:0,s:"PERSECUZIONE",c:[{r:"CONTROLLO",x:"REMOTO"},{r:"VILLEGGIATURA",x:"VACANZE"},{r:"PURA",x:"ACQUA"},{r:"DISCO",x:"FESTA"},{r:"GRANDEZZA",x:"ALTEZZA"}]},
  {id:20,w:"COLONNA",d:1,b:0,s:"INFAME",c:[{r:"FUMO",x:"ARROSTO"},{r:"ERCOLE",x:"FORZA"},{r:"SONORA",x:"LUCE"},{r:"QUINTA",x:"STRADA"},{r:"PORTANTE",x:"PARETE"}]},
  {id:21,w:"BUSTA",d:2,b:3,s:"CHIUSA",c:[{r:"PAGA",x:"DEBITO"},{r:"PRIMO",x:"VINCITORE"},{r:"PIATTO",x:"FONDO"},{r:"INDIRIZZO",x:"VIA"},{r:"CUORE",x:"BATTITO"}]},
  {id:22,w:"LOGGIA",d:2,b:2,s:"MASSONICA",c:[{r:"PALAZZO",x:"CASTELLO"},{r:"NERA",x:"CRONACA"},{r:"D'ONORE",x:"MERITO"},{r:"SCOPERCHIATA",x:"PENTOLA"},{r:"VATICANA",x:"MUSEO"}]},
  {id:23,w:"MASSA",d:2,b:1,s:"MAGRA",c:[{r:"CRITICA",x:"SITUAZIONE"},{r:"GRASSA",x:"OLIO"},{r:"LAVORO",x:"FATICA"},{r:"CARRARA",x:"MARMO"},{r:"URTO",x:"INCIDENTE"}]},
  {id:24,w:"SVILUPPO",d:1,b:4,s:"RULLINO",c:[{r:"SOSTENIBILE",x:"NATURA"},{r:"SOFTWARE",x:"COMPUTER"},{r:"PIANO",x:"PROGETTO"},{r:"RICERCA",x:"SCIENZA"},{r:"ECONOMICO",x:"SOLDI"}]},
  {id:25,w:"COMUNE",d:1,b:2,s:"SENTIERI",c:[{r:"MAL",x:"MALE"},{r:"TESTA",x:"CUORE"},{r:"MARE",x:"MONTI"},{r:"AMORE",x:"ODIO"},{r:"DENTI",x:"GENGIVE"}]},
  {id:26,w:"FRONTE",d:1,b:2,s:"FREDDO",c:[{r:"SOLDATO",x:"CROCE"},{r:"TESTA",x:"PIATTI"},{r:"BANCONOTA",x:"FIUMI"},{r:"VERSANTE",x:"MALE"},{r:"MONETA",x:"CALDO"}]},
  {id:27,w:"SEGNO",d:1,b:1,s:"ZODIACALE",c:[{r:"POLO",x:"NOME"},{r:"RISULTATO",x:"CUORE"},{r:"CARATTERE",x:"SELLA"},{r:"POSITIVO",x:"SECCHIO"},{r:"SENSAZIONE",x:"STELLA"}]},
  {id:28,w:"ORA",d:1,b:3,s:"LEGALE",c:[{r:"RELIGIONE",x:"ESATTE"},{r:"ESATTA",x:"SOLAMENTE"},{r:"SOLARE",x:"CUCINA"},{r:"PRANZO",x:"CAFFÈ"},{r:"THÈ",x:"GIUSTIZIA"}]},
  {id:29,w:"RADICE",d:1,b:2,s:"QUADRATA",c:[{r:"CALCOLATRICE",x:"FONTI"},{r:"CONTI",x:"ALBERO"},{r:"CE",x:"CEE"},{r:"SOLARE",x:"ORALE"},{r:"SCIENTIFICA",x:"LETTERALE"}]},
  {id:30,w:"SPECCHIO",d:1,b:2,s:"RIFLESSO",c:[{r:"ROMPERE",x:"STORCERE"},{r:"GUARDARSI",x:"SENTIRSI"},{r:"CORNICE",x:"CORNETTO"},{r:"MURO",x:"DURO"},{r:"IMMAGINE",x:"JPEG"}]},
  {id:31,w:"SPINA",d:1,b:3,s:"PESCE",c:[{r:"BIRRA",x:"COCA COLA"},{r:"TESSUTO",x:"TRAMA"},{r:"ROSA",x:"FOCA"},{r:"CALCAGNO",x:"BRACCIO"},{r:"CORRENTE",x:"RIVA"}]},
  {id:32,w:"FRUTTO",d:1,b:4,s:"BOSCO",c:[{r:"STAGIONE",x:"MESE"},{r:"PASSIONE",x:"PASSIONI"},{r:"PROIBITO",x:"PROBABILE"},{r:"PIANTA",x:"RADICE"},{r:"MARE",x:"GARE"}]},
  {id:33,w:"PENNELLO",d:1,b:1,s:"CILINDRO",c:[{r:"CALZA",x:"SCARPA"},{r:"BARBA",x:"CAPELLI"},{r:"ASCIUTTO",x:"BAGNATO"},{r:"PELI",x:"PALE"},{r:"TRUCCO",x:"TACCO"}]},
  {id:34,w:"ACHILLE",d:1,b:4,s:"OMERO",c:[{r:"EROE",x:"EROI"},{r:"CONDOTTIERO",x:"SENATORE"},{r:"GRECIA",x:"SPAGNA"},{r:"TALLONE",x:"SPALLA"},{r:"PIÈ",x:"OSSO"}]},
  {id:35,w:"DONNA",d:1,b:2,s:"CARRIERA",c:[{r:"MODERNA",x:"ANTICA"},{r:"AMICO",x:"NEMICO"},{r:"TRUCCO",x:"TENDA"},{r:"VITA",x:"VITI"},{r:"PASSATA",x:"PENSIONE"}]},
  {id:36,w:"NEVE",d:1,b:2,s:"FRESCA",c:[{r:"BIANCA",x:"ROSSA"},{r:"SPALA",x:"PALA"},{r:"FINTA",x:"VERA"},{r:"BATTUTA",x:"SBATTUTA"},{r:"CATENE",x:"CHIODI"}]},
  {id:37,w:"CAPELLI",d:1,b:1,s:"RICCI",c:[{r:"CADUTA",x:"CADERE"},{r:"ANGELO",x:"DIAVOLO"},{r:"TESTA",x:"TESTARDO"},{r:"COLORE",x:"BUIO"},{r:"SCIOLTI",x:"SCIOLTO"}]},
  {id:38,w:"OROLOGIO",d:1,b:3,s:"SABBIA",c:[{r:"POLSO",x:"GAMBA"},{r:"TASCHINO",x:"CAMICIA"},{r:"MURO",x:"CUCINA"},{r:"CAMPANILE",x:"SAGRATO"},{r:"STAZIONE",x:"MUNICIPIO"}]},
  {id:39,w:"TASTIERA",d:1,b:3,s:"NUMERICA",c:[{r:"COMPUTER",x:"MONITOR"},{r:"TELEFONINO",x:"LAVATRICE"},{r:"CALCOLATRICE",x:"ABACO"},{r:"PIANOFORTE",x:"ARPA"},{r:"ERGONOMICA",x:"EGOCENTRICA"}]},
  {id:40,w:"CASCO",d:1,b:2,s:"INTEGRALE",c:[{r:"CAPELLI",x:"CAPPELLI"},{r:"MOTO",x:"BARCA"},{r:"BANANE",x:"CILIEGE"},{r:"FORMULA 1",x:"FORMULA CHIMICA"},{r:"SCODELLA",x:"PADELLA"}]},
  {id:41,w:"CLESSIDRA",d:1,b:1,s:"VETRO",c:[{r:"SABBIA",x:"MARE"},{r:"TEMPO",x:"SOLE"},{r:"GIOCO DI RUOLO",x:"GIOCO DI SOCIETÀ"},{r:"GRECIA",x:"SPAGNA"},{r:"FORO",x:"ENTRATA"}]},
  {id:42,w:"POTABILE",d:1,b:4,s:"ACQUA",c:[{r:"SALATA",x:"PIENA"},{r:"SCOLO",x:"RICIRCOLO"},{r:"DISTILLATA",x:"ETERNA"},{r:"DOLCE",x:"AMARA"},{r:"MINERALE",x:"LIBERA"}]},
  {id:43,w:"CIOCCOLATO",d:1,b:2,s:"FONDENTE",c:[{r:"LEZIONI",x:"FAI DA TE"},{r:"BIANCO",x:"VERDE"},{r:"NERO",x:"GIALLO"},{r:"MANDORLE",x:"AGRUMI"},{r:"CONCENTRATO",x:"RILASSATO"}]},
  {id:44,w:"BORSA",d:1,b:0,s:"STUDIO",c:[{r:"GHIACCIO",x:"NEVE"},{r:"SPESA",x:"TESA"},{r:"DONNA",x:"GONNA"},{r:"VIAGGIO",x:"LACCIO"},{r:"PELLE",x:"CELLE"}]},
  {id:45,w:"RIVISTA",d:1,b:1,s:"MODA",c:[{r:"SETTIMANALE",x:"AMARE"},{r:"VISTA",x:"SENTITA"},{r:"TIRATURA",x:"SPECIE"},{r:"PESCA",x:"ANNUALE"},{r:"ANNUALE",x:"SALE"}]},
  {id:46,w:"OCCHIALI",d:1,b:3,s:"VISTA",c:[{r:"SOLE",x:"VENTO"},{r:"NERI",x:"AMARI"},{r:"GOCCIA",x:"SENTENZA"},{r:"SCURI",x:"RICHARD"},{r:"VINTAGE",x:"LENTI"}]},
  {id:47,w:"TIMBRO",d:1,b:3,s:"UFFICIO",c:[{r:"POSTALE",x:"POSTE"},{r:"VOCE",x:"GOLA"},{r:"MANUALE",x:"AUTOMATICO"},{r:"INCHIOSTRO",x:"IMPIASTRO"},{r:"QUALITÀ",x:"AMICIZIA"}]},
  {id:48,w:"PRESA",d:1,b:2,s:"DIRETTA",c:[{r:"CORRENTE",x:"CALMA"},{r:"POSIZIONE",x:"ATTESA"},{r:"MURO",x:"SEDIA"},{r:"MULTIPLA",x:"SEDUCENTE"},{r:"AEREA",x:"TERRENA"}]},
  {id:49,w:"MASCHERA",d:1,b:1,s:"SUB",c:[{r:"BENESSERE",x:"MALESSERE"},{r:"TRUCCO",x:"STRUCCO"},{r:"FACCIA",x:"GAMBA"},{r:"CARNEVALE",x:"NATALE"},{r:"ZORRO",x:"MIKEY MOUSE"}]},
  {id:50,w:"MULTIPLA",d:1,b:4,s:"SCELTA",c:[{r:"AUTO",x:"MOTO"},{r:"PRESA",x:"LASCIATA"},{r:"MALATTIA",x:"BENESSERE"},{r:"ENTRATA",x:"USCITA"},{r:"SALITA",x:"CADUTA"}]},
  {id:51,w:"SCIARPA",d:1,b:2,s:"SETA",c:[{r:"INVERNO",x:"ESTATE"},{r:"TIFOSO",x:"MAGO"},{r:"LANA",x:"VETRO"},{r:"ARTIGIANALE",x:"MECCANICA"},{r:"NODO",x:"GOLA"}]},
  {id:52,w:"CUFFIA",d:1,b:2,s:"LANA",c:[{r:"NUOTO",x:"CALCIO"},{r:"MUSICA",x:"LAVORO"},{r:"PANETTIERE",x:"BANCHIERE"},{r:"DOCCIA",x:"BAGNO"},{r:"WIRELESS",x:"ELETTRICA"}]},
  {id:53,w:"PORTAFOGLIO",d:1,b:1,s:"TITOLI",c:[{r:"CARTE",x:"CODICI"},{r:"SOLDI",x:"SALE"},{r:"TASCA",x:"FRASCA"},{r:"DOCUMENTI",x:"LIBERATORIE"},{r:"PATENTE",x:"LICENZA"}]},
  {id:54,w:"BOLLA",d:1,b:3,s:"SPECULATIVA",c:[{r:"SAPONE",x:"DETERSIVO"},{r:"ACCOMPAGNAMENTO",x:"SOSTENIMENTO"},{r:"GASTRICA",x:"MENTALE"},{r:"IMMOBILIARE",x:"VIRALE"},{r:"SCOTTATURA",x:"SELEZIONARE"}]},
  {id:55,w:"RADIO",d:1,b:4,s:"FARO",c:[{r:"MUSICA",x:"MOSCA"},{r:"101",x:"102"},{r:"ASCOLTARE",x:"CANTARE"},{r:"CLASSIFICA",x:"GARA"},{r:"ONLINE",x:"CARTACEA"}]},
  {id:56,w:"CALENDARIO",d:1,b:2,s:"AVVENTO",c:[{r:"SANTI",x:"EROI"},{r:"MESE",x:"PASSATO"},{r:"PIRELLI",x:"MICHELIN"},{r:"SERIE A",x:"LIBERO"},{r:"FESTIVITÀ",x:"PAROLE"}]},
  {id:57,w:"MOUSE",d:1,b:3,s:"PAD",c:[{r:"FORMAGGIO",x:"LATTUGA"},{r:"GATTO",x:"VOLPE"},{r:"COMPUTER",x:"TELEFONO"},{r:"CODA",x:"FRANGETTA"},{r:"INGLESE",x:"FRANCESE"}]},
  {id:58,w:"CINTURA",d:1,b:2,s:"SICUREZZA",c:[{r:"PELLE",x:"CARNE"},{r:"PALESTRA",x:"BAGNO"},{r:"DIMAGRANTE",x:"STIMOLANTE"},{r:"CASTITÀ",x:"EREMITA"},{r:"LOMBARE",x:"SCAPOLARE"}]},
  {id:59,w:"CASSE",d:1,b:1,s:"MORTO",c:[{r:"DISCOTECA",x:"STADIO"},{r:"AUTO",x:"MOTO"},{r:"FRUTTA",x:"VERDURA"},{r:"CONCERTO",x:"CIMITERO"},{r:"PC",x:"PENNA"}]},
  {id:60,w:"FOTO",d:1,b:4,s:"SEGNALETICA",c:[{r:"ALBUM",x:"GOMME"},{r:"STAMPA",x:"CAMPA"},{r:"MATRIMONIO",x:"FUNERALE"},{r:"CORNICE",x:"DENTE"},{r:"GRUPPO",x:"LUPO"}]},
  {id:61,w:"BANDA",d:1,b:2,s:"LARGA",c:[{r:"ELASTICA",x:"DURA"},{r:"LARGHEZZA",x:"LUNGHEZZA"},{r:"MUSICALE",x:"OVALE"},{r:"MAGLIANA",x:"MAGLIERIA"},{r:"PAESE",x:"CITTÀ"}]},
  {id:62,w:"SVEGLIA",d:1,b:0,s:"LANCETTA",c:[{r:"RADIO",x:"TV"},{r:"MATTINO",x:"POMERIGGIO"},{r:"OROLOGIO",x:"CAMPANILE"},{r:"PROGRAMMA",x:"SENTENZA"},{r:"COMODINO",x:"FRIGO"}]},
  {id:63,w:"NERVI",d:1,b:1,s:"SALDI",c:[{r:"GENOVA",x:"PARIGI"},{r:"SPINALI",x:"SPIRALI"},{r:"INFIAMMATI",x:"SPENTI"},{r:"DIREZIONALITÀ",x:"CADENZA"},{r:"OTTICO",x:"UDITIVO"}]},
  {id:64,w:"ISOLA",d:1,b:3,s:"TESORO",c:[{r:"FELICE",x:"INFELICE"},{r:"PEDONALE",x:"TRAFFICO"},{r:"TV",x:"RADIO"},{r:"NON C'È",x:"CI SARÀ"},{r:"FAMOSI",x:"SUPREMI"}]},
  {id:65,w:"BAZAR",d:1,b:4,s:"APERTO",c:[{r:"BARATTO",x:"LAVORO"},{r:"GRUPPO MUSICALE",x:"ORCHESTRA"},{r:"GRAN",x:"PICCOLO"},{r:"PERSIANO",x:"BABILONESE"},{r:"SUQ",x:"SUV"}]},
  {id:66,w:"TENDA",d:1,b:2,s:"OSSIGENO",c:[{r:"SOLE",x:"MARE"},{r:"CAMPEGGIO",x:"HOTEL"},{r:"ESTERNO",x:"INTERNO"},{r:"CANADESE",x:"AMERICANA"},{r:"SIPARIO",x:"LOGGIONE"}]},
  {id:67,w:"TAVOLA",d:1,b:3,s:"VELA",c:[{r:"LEGNO",x:"PIETRA"},{r:"DERIVATE",x:"SIGNIFICATI"},{r:"SURF",x:"CALCIO"},{r:"COLORI",x:"BIANCO E NERO"},{r:"PITAGORICA",x:"SOCRATICA"}]},
  {id:68,w:"BOTTI",d:1,b:0,s:"RISPOSTA",c:[{r:"VINO",x:"PESCA"},{r:"LEGNO",x:"CERAMICA"},{r:"CAPODANNO",x:"NATALE"},{r:"RECIPIENTE",x:"RECINTO"},{r:"CANTINA",x:"LUNA"}]},
  {id:69,w:"TAPPO",d:1,b:1,s:"CORONA",c:[{r:"INGLESE",x:"FRANCESE"},{r:"SUGHERO",x:"PAPAIA"},{r:"BASSO",x:"ALTO"},{r:"BOTTIGLIA",x:"MANO"},{r:"SAPORE",x:"ODORE"}]},
  {id:70,w:"IMPIANTO",d:1,b:4,s:"FRENANTE",c:[{r:"OVULO",x:"CELLULA"},{r:"STEREO",x:"PLAY STATION"},{r:"GEOTERMICO",x:"SISMICO"},{r:"IRRIGAZIONE",x:"SICCITÀ"},{r:"ELETTRICO",x:"STATICO"}]},
  {id:71,w:"CANCELLO",d:1,b:2,s:"AUTOMATICO",c:[{r:"SCORREVOLE",x:"INTASATO"},{r:"TELECOMANDO",x:"RADIOCOMANDO"},{r:"FERRO",x:"PORCELLANA"},{r:"ENTRATA",x:"GIUSTIZIA"},{r:"SICUREZZA",x:"ERRORE"}]},
  {id:72,w:"TRECCIA",d:1,b:2,s:"AGLIO",c:[{r:"DOLCE",x:"AMARA"},{r:"RUSSA",x:"FRANCESE"},{r:"LATTICINO",x:"INSACCATO"},{r:"PASQUALE",x:"NATALIZIA"},{r:"CAPELLI",x:"OCCHI"}]},
  {id:73,w:"STADIO",d:1,b:1,s:"CALCIO",c:[{r:"ULTIMO",x:"PRIMO"},{r:"GRUPPO",x:"SINGOLO"},{r:"SCOPERTO",x:"INDOOR"},{r:"CURVA",x:"RETTA"},{r:"BIGLIETTO",x:"LIBERO"}]},
  {id:74,w:"AEREO",d:1,b:3,s:"VETTORE",c:[{r:"BAGAGLIO",x:"TAKE AWAY"},{r:"COMPAGNIE",x:"SOLITUDINE"},{r:"BIGLIETTO",x:"PASS"},{r:"PONTE",x:"SALTA"},{r:"STRADA",x:"CADE"}]},
  {id:75,w:"TRONCO",d:1,b:2,s:"CONO",c:[{r:"DOLCE",x:"AMARO"},{r:"POLMONARE",x:"CEREBRALE"},{r:"COMUNE",x:"DIFFICILE"},{r:"ALBERO",x:"CESPUGLIO"},{r:"FIUME",x:"CASCATA"}]},
  {id:76,w:"CARRELLO",d:1,b:0,s:"ATTERRAGGIO",c:[{r:"AUTO",x:"MOTO"},{r:"VIRTUALE",x:"STATICO"},{r:"RIMORCHIO",x:"ROTORE"},{r:"SPESA",x:"RISPARMIO"},{r:"GETTONIERA",x:"OFFERTA"}]},
  {id:77,w:"CATENA",d:1,b:3,s:"ALIMENTARE",c:[{r:"REAZIONE",x:"AZIONE"},{r:"CANCELLO",x:"PORTA"},{r:"BICICLETTA",x:"MACCHINA"},{r:"MONTUOSA",x:"COLLINARE"},{r:"MONTAGGIO",x:"SMONTAGGIO"}]},
  {id:78,w:"LAMPADINA",d:1,b:2,s:"RISPARMIO",c:[{r:"IDEA",x:"COPIARE"},{r:"ACCENDERE",x:"INTERROMPERE"},{r:"INVENZIONE",x:"SCOPERTA"},{r:"ALOGENA",x:"FILTRO"},{r:"VETRO",x:"PETROLIO"}]},
  {id:79,w:"POSTA",d:1,b:1,s:"PRIORITARIA",c:[{r:"ELETTRONICA",x:"DINAMICA"},{r:"BANCO",x:"BANCONE"},{r:"ORARI",x:"DATE"},{r:"SPEDIZIONE",x:"INVIARE"},{r:"SPORTELLO",x:"ACCELERATORE"}]},
  {id:80,w:"SEDIA",d:1,b:4,s:"SDRAIO",c:[{r:"ROTELLE",x:"STAMPELLE"},{r:"UFFICIO",x:"POSTA"},{r:"GESTATORIA",x:"EROICA"},{r:"ELETTRICA",x:"EOLICA"},{r:"ERGONOMICA",x:"FISSA"}]},
  {id:81,w:"STAFFA",d:1,b:0,s:"PERDERE",c:[{r:"BANCA INTESA",x:"DISCORDIA"},{r:"SPORTELLO",x:"RUOTA"},{r:"SELLA",x:"STAFF"},{r:"ITALIA",x:"ESTERA"},{r:"FILA",x:"SALDO"}]},
  {id:82,w:"BAULE",d:1,b:0,s:"TETTO",c:[{r:"AUTO",x:"SEDIA"},{r:"MILITARE",x:"SOCIALE"},{r:"MAGICO",x:"STATICO"},{r:"PLASTICA",x:"VETRO"},{r:"VIAGGIO",x:"BICI"}]},
  {id:83,w:"VINO",d:1,b:1,s:"ROSSO",c:[{r:"PRODUZIONE",x:"RACCOLTA"},{r:"UVA",x:"ARANCIA"},{r:"ETICHETTE",x:"GRAFFETTE"},{r:"CALICI",x:"TAZZE"},{r:"BOTTE",x:"SFOTTE"}]},
  {id:84,w:"GIORNALE",d:1,b:3,s:"MURO",c:[{r:"RADIO",x:"VOLUME"},{r:"SETTIMANALE",x:"ANNUALE"},{r:"PERIODICO",x:"UNA TANTUM"},{r:"PAGINA",x:"MANIFESTO"},{r:"COPERTINA",x:"LIBRERIA"}]},
  {id:85,w:"RETE",d:1,b:2,s:"SOCIAL",c:[{r:"INTERNET",x:"DOMICILIARE"},{r:"PESCA",x:"CACCIA"},{r:"DOMESTICA",x:"ESTERNA"},{r:"CANALE 5",x:"RADIO"},{r:"COMPUTER",x:"CALCOLATRICI"}]},
  {id:86,w:"SMALTO",d:1,b:2,s:"ROSSETTO",c:[{r:"UNGHIE",x:"CIGLIA"},{r:"GEL",x:"ROSSO"},{r:"DENTI",x:"LABBRA"},{r:"BRILLANTEZZA",x:"CAPARBIETÀ"},{r:"VERNICE",x:"COLLA"}]},
  {id:87,w:"LETTERA",d:1,b:3,s:"MORTA",c:[{r:"AMORE",x:"ODIO"},{r:"FORMALE",x:"LIBERA"},{r:"MODELLO",x:"MODELLA"},{r:"PRESENTAZIONE",x:"RIFUGIO"},{r:"COMMERCIALE",x:"NO PROFIT"}]},
  {id:88,w:"TERRA",d:1,b:2,s:"PROMESSA",c:[{r:"CIRCONFERENZA",x:"CERCHIO"},{r:"MADRE",x:"FIGLIA"},{r:"SANTA",x:"LAICA"},{r:"LIBERA",x:"STACCATA"},{r:"NUOVA",x:"VECCHIA"}]},
  {id:89,w:"ORIGINE",d:1,b:1,s:"CONTROLLATA",c:[{r:"MISTERIOSA",x:"LIMPIDA"},{r:"STRANIERA",x:"COMUNITARIA"},{r:"PAESE",x:"CONTINENTE"},{r:"PAROLE",x:"FRASI"},{r:"UOMO",x:"DONNA"}]},
  {id:90,w:"LIMONE",d:1,b:4,s:"SPREMUTA",c:[{r:"GELATO",x:"SPESE"},{r:"TORTA",x:"LIQUIRIZIA"},{r:"FRUTTO",x:"FRUTTA"},{r:"DIETA",x:"FAST FOOD"},{r:"ALBERO",x:"QUERCIA"}]},
  {id:91,w:"FRENO",d:1,b:2,s:"STAZIONAMENTO",c:[{r:"MANO",x:"POLSO"},{r:"MOTORE",x:"MOTORINO"},{r:"PASTIGLIE",x:"BUSTINE"},{r:"DISCHI",x:"CERCHI"},{r:"INIBITORE",x:"ESPANSIVO"}]},
  {id:92,w:"CARRETTO",d:1,b:2,s:"TRAINATO",c:[{r:"SICILIANO",x:"PUGLIESE"},{r:"BAMBINI",x:"ADULTI"},{r:"CREPES",x:"POLLO"},{r:"GELATI",x:"BARCHE"},{r:"CARLO",x:"FABIO"}]},
  {id:93,w:"COLAZIONE",d:1,b:1,s:"SACCO",c:[{r:"INGLESE",x:"THAILANDESE"},{r:"EQUILIBRATA",x:"PAZZA"},{r:"LETTO",x:"DIVANO"},{r:"PRIMA",x:"ULTIMA"},{r:"TIFFANY",x:"CHANEL"}]},
  {id:94,w:"CARTELLA",d:1,b:3,s:"ESATTORIALE",c:[{r:"FARE",x:"DARE"},{r:"TRADUZIONE",x:"SIRENA"},{r:"INFORMATICA",x:"LOGICA"},{r:"STAMPA",x:"ZAMPA"},{r:"CLINICA",x:"CINICA"}]},
  {id:95,w:"BASE",d:1,b:0,s:"DATI",c:[{r:"SCARPE",x:"LADRO"},{r:"RAGGIUNGERE",x:"CONGIUNGERE"},{r:"GEOMETRIA",x:"TRIGONOMETRIA"},{r:"NAUTICA",x:"DIZIONARIO"},{r:"TARIFFA",x:"PROPOSTA"}]},
  {id:96,w:"LAVORO",d:1,b:2,s:"FORZA",c:[{r:"OFFERTA",x:"DURO"},{r:"VIAGGI",x:"NOTIZIE"},{r:"DOMANDA",x:"PERCHÉ?"},{r:"SPECIALE",x:"NORMALE"},{r:"TROVA",x:"DECIDI"}]},
  {id:97,w:"LETTO",d:1,b:3,s:"DIVANO",c:[{r:"VASSOIO",x:"CUSCINO"},{r:"ASSORBENTE",x:"IDRATANTE"},{r:"GIREVOLE",x:"PIEGHEVOLE"},{r:"BICCHIERI",x:"CARTONE"},{r:"ACCIAIO",x:"LENTO"}]},
  {id:98,w:"RINGHIERA",d:1,b:2,s:"SCALE",c:[{r:"PROTETTIVA",x:"PERICOLOSA"},{r:"VERNICIARE",x:"SALIRE"},{r:"SALTARE",x:"BACIARE"},{r:"TEATRO",x:"STADIO"},{r:"FERRO",x:"BOTULINO"}]},
  {id:99,w:"TAVOLO",d:1,b:1,s:"ROTONDO",c:[{r:"ALLUNGABILE",x:"SCONFITTA"},{r:"PIEGHEVOLE",x:"DUREVOLE"},{r:"BILIARDO",x:"BILIARDINO"},{r:"CONSOLLE",x:"FAX"},{r:"CUCINA",x:"BAGNO"}]},
  {id:100,w:"ZERO",d:1,b:4,s:"ASSOLUTO",c:[{r:"SPARARE",x:"DUE"},{r:"ALTEZZA",x:"BASSEZZA"},{r:"SALVE",x:"PREGO"},{r:"ARIA",x:"FUOCO"},{r:"BERSAGLIO",x:"PUNTO"}]},
  {id:101,w:"SCATOLA",d:1,b:2,s:"SCARPE",c:[{r:"CINEMA",x:"ITALIANA"},{r:"SCARPE",x:"SCALE"},{r:"GIOCO",x:"DIVERTENTE"},{r:"NERA",x:"VERDE"},{r:"LEGNO",x:"MAGRO"}]},
  {id:102,w:"SCARTO",d:1,b:2,s:"DIFFERENZA",c:[{r:"CARTE",x:"CREDITO"},{r:"CIBO",x:"BUONO"},{r:"MATEMATICA",x:"ITALIANO"},{r:"MATERIALE",x:"DURO"},{r:"TONER",x:"STAMPANTE"}]},
  {id:103,w:"TEST",d:1,b:1,s:"INGRESSO",c:[{r:"CRASH",x:"DASH"},{r:"AMMISSIONE",x:"UNIVERSITARIA"},{r:"LOGICA",x:"EMPIRICA"},{r:"PERSONALITÀ",x:"DISTURBATA"},{r:"GRAVIDANZA",x:"PERICOLOSA"}]},
  {id:104,w:"LINEA",d:1,b:3,s:"CONFINE",c:[{r:"DIRETTA",x:"DIFFERITA"},{r:"GEOMETRICA",x:"TONDA"},{r:"BLU",x:"VERDE"},{r:"FERROVIARIA",x:"TIR"},{r:"IN",x:"ON"}]},
  {id:105,w:"ROTOLO",d:1,b:0,s:"CARTA",c:[{r:"PANCIA",x:"TESTA"},{r:"FARCITO",x:"SCONDITO"},{r:"CIOCCOLATO",x:"SALATO"},{r:"SCOTTEX",x:"PAPERA"},{r:"RIPIENO",x:"RITAGLIO"}]},
  {id:106,w:"STATUETTA",d:1,b:2,s:"ORO",c:[{r:"BRONZO",x:"DESTRA"},{r:"OSCAR",x:"SCALFARO"},{r:"DUOMO",x:"PIAZZA"},{r:"MINIATURA",x:"GRANDEZZA"},{r:"SOLDATO",x:"SPARO"}]},
  {id:107,w:"ENTRATA",d:1,b:3,s:"SECONDARIA",c:[{r:"SERVIZIO",x:"STABILE"},{r:"PRINCIPALE",x:"SECONDA"},{r:"IN VIGORE",x:"IN USCITA"},{r:"MERCI",x:"MERCÌ"},{r:"LIBERA",x:"SPARATORIA"}]},
  {id:108,w:"SEGRETERIA",d:1,b:2,s:"PARTITO",c:[{r:"VIRTUALE",x:"SALDO"},{r:"TELEFONICA",x:"POSTALE"},{r:"UNIVERSITÀ",x:"ITALIANA"},{r:"STUDENTI",x:"DOCENTI"},{r:"STATO",x:"FRANCESE"}]},
  {id:109,w:"AUTOSTRADA",d:1,b:1,s:"SOLE",c:[{r:"A1",x:"BATTAGLIA NAVALE"},{r:"LAVORI",x:"FERIALI"},{r:"CISA",x:"VISA"},{r:"TRAFFICO",x:"MAESTRO"},{r:"PEDAGGIO",x:"SCONTO"}]},
  {id:110,w:"SERVO",d:1,b:4,s:"MUTO",c:[{r:"COMANDO",x:"BATTAGLIA"},{r:"PER AMORE",x:"PER DIETA"},{r:"GLEBA",x:"GIBILTERRA"},{r:"STERZO",x:"RUOTA"},{r:"DIO",x:"BUDDHA"}]},
  {id:111,w:"STAZIONE",d:1,b:2,s:"SPAZIALE",c:[{r:"CELESTE",x:"VERDE"},{r:"PARTENZA",x:"DIRIGIBILE"},{r:"BICICLETTE",x:"MOTO"},{r:"CENTRALE",x:"BIPOLARE"},{r:"GRANDE",x:"VOLABILE"}]},
  {id:112,w:"PRIMO",d:1,b:0,s:"PIATTO",c:[{r:"GIORNO",x:"DELTA"},{r:"CANALE",x:"SUEZ"},{r:"BACIO",x:"LINGUA"},{r:"SOCCORSO",x:"AIUTO"},{r:"APPUNTAMENTO",x:"SERIO"}]},
  {id:113,w:"SCARPA",d:1,b:1,s:"CALZANTE",c:[{r:"SCI",x:"COLLINA"},{r:"MONTAGNA",x:"FIUME"},{r:"TACCO",x:"STACCO"},{r:"LACCIO",x:"SETACCIO"},{r:"ORO",x:"METALLO"}]},
  {id:114,w:"FEDELTÀ",d:1,b:3,s:"PREMIO",c:[{r:"SUONO",x:"AMABILE"},{r:"CONIUGALE",x:"MADRE"},{r:"CARTA",x:"PESO"},{r:"ALTA",x:"SALTA"},{r:"MARITO",x:"MARITOZZO"}]},
  {id:115,w:"PARTITA",d:1,b:2,s:"SCACCHI",c:[{r:"CUORE",x:"POLMONE"},{r:"DIFFICILE",x:"SALTARE"},{r:"LIVE",x:"LOVE"},{r:"NAZIONALE",x:"AZZURRI"},{r:"VITA",x:"VOTO"}]},
  {id:116,w:"CUORE",d:1,b:2,s:"PIETRA",c:[{r:"LATTA",x:"MASCHIO"},{r:"ROBOT",x:"AUTO"},{r:"TARGA",x:"PARGA"},{r:"UOMO",x:"VENA"},{r:"SCATOLE",x:"ROMPERE"}]},
  {id:117,w:"TACCO",d:1,b:3,s:"PUNTA",c:[{r:"PASSAGGIO",x:"PRATO"},{r:"STIVALE",x:"ITALIANO"},{r:"ALTO",x:"LUNGO"},{r:"SPILLO",x:"ALTOBELLI"},{r:"GOL",x:"GALLES"}]},
  {id:118,w:"FORTUNA",d:1,b:2,s:"RUOTA",c:[{r:"PORTARE",x:"LASCIARE"},{r:"SPECCHIO",x:"BRAME"},{r:"BISCOTTO",x:"COTTO"},{r:"OROSCOPO",x:"GEMELLI"},{r:"BACIATO",x:"BOCCA"}]},
  {id:119,w:"BIDONE",d:1,b:1,s:"SPAZZATURA",c:[{r:"RIFIUTI",x:"SOLIDI"},{r:"APPUNTAMENTO",x:"TERRA"},{r:"ETICHETTA",x:"RACCHETTA"},{r:"NUCLEARE",x:"ATOMICO"},{r:"CALCIATORE",x:"SPAGNOLO"}]},
  {id:120,w:"TRENO",d:1,b:4,s:"MERCI",c:[{r:"VELOCE",x:"SUPER"},{r:"SIMULATORE",x:"VOLO"},{r:"ABBONAMENTO",x:"BUS"},{r:"SCAMBIO",x:"SALTO"},{r:"PORTA",x:"TORTA"}]},
  {id:121,w:"PESO",d:1,b:0,s:"LORDO",c:[{r:"FORMA",x:"TONDA"},{r:"IDEALE",x:"IDEALISTA"},{r:"SPECIFICO",x:"MANIGLIE"},{r:"CALCOLO",x:"UNITÀ"},{r:"ORO",x:"ARGENTO"}]},
  {id:122,w:"SCADENZA",d:1,b:2,s:"BREVE",c:[{r:"730",x:"DIRETTA"},{r:"DATA",x:"PALINSESTO"},{r:"FISCALE",x:"RODITORE"},{r:"CONCORSO",x:"ANNUALE"},{r:"TERMINI",x:"STAZIONE"}]},
  {id:123,w:"SPESA",d:1,b:1,s:"PELLE",c:[{r:"AMICA",x:"NEMICA"},{r:"CARRELLO",x:"TENDA"},{r:"LISTA",x:"PISTA"},{r:"PUBBLICA",x:"PELLE"},{r:"INTELLIGENTE",x:"SCEMA"}]},
  {id:124,w:"PROFUMO",d:1,b:3,s:"DONNA",c:[{r:"UOMO",x:"LETTO"},{r:"NATURALE",x:"IBRIDO"},{r:"AMBIENTE",x:"STABILE"},{r:"PULITO",x:"SPORCO"},{r:"AMPOLLA",x:"SUCCESSO"}]},
  {id:125,w:"BANCA",d:1,b:0,s:"DATI",c:[{r:"SOLDI",x:"SPESI"},{r:"POPOLARE",x:"IMPOPOLARE"},{r:"SPORTELLO",x:"AUTO"},{r:"CHIUSA",x:"ARGINE"},{r:"SCOPERTO",x:"COPERTO"}]},
  {id:126,w:"FOGLIO",d:1,b:0,s:"BIANCO",c:[{r:"CARTA",x:"PAPERA"},{r:"ROSA",x:"GIALLA"},{r:"GIORNALE",x:"SPORCO"},{r:"CALCOLO",x:"TRIANGOLO"},{r:"COMPLEMENTARE",x:"DIAGONALE"}]},
  {id:127,w:"OSTACOLO",d:1,b:3,s:"CORSA",c:[{r:"SALTO",x:"PANDA"},{r:"OLTRE",x:"DIVERSO"},{r:"SUPERARE",x:"CAMMINARE"},{r:"CAVALLO",x:"PECORA"},{r:"AGGIRARE",x:"GIRARE"}]},
  {id:128,w:"BINARIO",d:1,b:0,s:"MORTO",c:[{r:"SISTEMA",x:"AZIONE"},{r:"ALFABETO",x:"INDIANO"},{r:"CALCOLO",x:"MATEMATICO"},{r:"PRINCIPALE",x:"SEGRETARIA"},{r:"FERROVIARIO",x:"BUS"}]},
  {id:129,w:"LIVELLO",d:1,b:1,s:"MARE",c:[{r:"BATTERIA",x:"MACCHINA"},{r:"CONTRATTUALE",x:"ANNUALE"},{r:"FIUME",x:"PIENA"},{r:"EUROPEO",x:"AMERICANO"},{r:"LOCALE",x:"SPAZIALE"}]},
  {id:130,w:"CINEMA",d:1,b:4,s:"SALA",c:[{r:"MUTO",x:"VESTITO"},{r:"CERCARE",x:"DIFFICILE"},{r:"ITALIANO",x:"MEDIO"},{r:"AUTORE",x:"SCRITTORE"},{r:"OGGI",x:"SEDUTI"}]},
  {id:131,w:"FRANA",d:1,b:0,s:"TERRENO",c:[{r:"STUDIO",x:"SINDACO"},{r:"DISASTRO",x:"PETARDO"},{r:"NEVE",x:"MARE"},{r:"MONITORAGGIO",x:"SERPENTE"},{r:"DISBOSCAMENTO",x:"ALBERI"}]},
  {id:132,w:"MONDO",d:1,b:2,s:"NUOVO",c:[{r:"MAPPA",x:"GEROGLIFICO"},{r:"CARTINA",x:"TORNASOLE"},{r:"NOTIZIE",x:"CATTIVE"},{r:"SOLIDALE",x:"AFFETTUOSO"},{r:"MARCIO",x:"PESTO"}]},
  {id:133,w:"MEDICINA",d:1,b:1,s:"GENERALE",c:[{r:"FACOLTÀ",x:"FACOLTOSO"},{r:"STUDIARE",x:"RIPETERE"},{r:"COMUNE",x:"ERBE"},{r:"SPORTIVA",x:"CAMPO"},{r:"LEGALE",x:"CALCIO"}]},
  {id:134,w:"POSTER",d:1,b:3,s:"MANIFESTO",c:[{r:"GIGANTE",x:"MEDIO"},{r:"FILM",x:"AMORE"},{r:"PUBBLICITÀ",x:"PROGRESSO"},{r:"MULTIFUNZIONE",x:"APERTA"},{r:"MOTIVAZIONALE",x:"ARABO"}]},
  {id:135,w:"CANALE",d:1,b:2,s:"SUEZ",c:[{r:"ACQUA",x:"PAROLE"},{r:"TV",x:"SPETTRO"},{r:"PROGRAMMI",x:"SBAGLIATI"},{r:"KIDS",x:"KEEP"},{r:"5",x:"25"}]},
  {id:136,w:"SCORTA",d:1,b:2,s:"MAGAZZINO",c:[{r:"RUOTA",x:"PARABREZZA"},{r:"POLITICO",x:"ARMATORE"},{r:"SERVIZIO",x:"SICURO"},{r:"MINIMA",x:"MASSIMA"},{r:"CIBO",x:"ACQUATICA"}]},
  {id:137,w:"PARERE",d:1,b:3,s:"ESPERTO",c:[{r:"CONTRARIO",x:"CERTO"},{r:"OPPOSTO",x:"DIO"},{r:"TUO",x:"NOI"},{r:"CONFORME",x:"SCATOLA"},{r:"GIURIDICO",x:"LEGISLATORE"}]},
  {id:138,w:"DISCOTECA",d:1,b:4,s:"NOTTE",c:[{r:"BALLARE",x:"INFERNO"},{r:"PISTA",x:"GHIACCIO"},{r:"MUSICA",x:"FORTE"},{r:"ESTIVA",x:"STAGIONALE"},{r:"LUCI",x:"LUCERTOLE"}]},
  {id:139,w:"GALLERIA",d:1,b:1,s:"ARTE",c:[{r:"MILANO",x:"TORINO"},{r:"BORGHESE",x:"PROLETARIO"},{r:"AUTO",x:"STECCA"},{r:"NAZIONALE",x:"POPOLARE"},{r:"IMMAGINI",x:"VECCHIE"}]},
  {id:140,w:"MONDIALE",d:1,b:4,s:"CAMPIONATO",c:[{r:"MOTO",x:"AUTO"},{r:"CALCIO",x:"SUPER"},{r:"CLUB",x:"STRIP"},{r:"OROLOGIO",x:"LANCETTA"},{r:"GIORNATA",x:"PASTORE"}]},
  {id:141,w:"TITOLI",d:1,b:2,s:"CODA",c:[{r:"TG",x:"GT"},{r:"BORSA",x:"GIÙ"},{r:"NOBILIARE",x:"PREGIUDICATO"},{r:"CONFINARIO",x:"COSTUME"},{r:"STUDIO",x:"LUSSO"}]},
  {id:142,w:"MANICO",d:1,b:2,s:"PENTOLA",c:[{r:"CHITARRA",x:"BATTERIA"},{r:"SCOPA",x:"TOPA"},{r:"USCIRE",x:"ENTRARE"},{r:"SOLLEVARE",x:"SALTARE"},{r:"OMBRELLO",x:"TELO"}]},
  {id:143,w:"SEGRETO",d:1,b:1,s:"TRUCCO",c:[{r:"TRUCCO",x:"MALATO"},{r:"VIDEOGIOCO",x:"IPAD"},{r:"SPOSA",x:"REALE"},{r:"OCCHI",x:"MANI"},{r:"MINERALE",x:"OLIGOMINERALE"}]},
  {id:144,w:"LEGO",d:1,b:3,s:"GIOCO",c:[{r:"COSTRUZIONE",x:"DEMOLIZIONE"},{r:"MATTONCINO",x:"PALA"},{r:"ISTRUZIONI",x:"SCRITTE"},{r:"CASTELLO",x:"ELEVATO"},{r:"OMINO",x:"DONNINA"}]},
  {id:145,w:"VIRUS",d:1,b:0,s:"INFORMATICA",c:[{r:"PC",x:"XBOX"},{r:"SOFTWARE",x:"HARDWARE"},{r:"PANDA",x:"ARMADILLO"},{r:"JOHN VON NEUMANN",x:"ALEX DEL PIERO"},{r:"DIFFUSIONE",x:"INTENZIONE"}]},
  {id:146,w:"BOMBA",d:1,b:2,s:"OROLOGERIA",c:[{r:"CARTA",x:"IGIENICA"},{r:"STORIA",x:"ANTICA"},{r:"NAVALE",x:"CANTIERE"},{r:"MARCO",x:"FRANCESCO"},{r:"TIPO",x:"TIPETTO"}]},
  {id:147,w:"SPECIALISTA",d:1,b:3,s:"VISITA",c:[{r:"MEDICO",x:"FRUTTIVENDOLO"},{r:"RISPONDE",x:"DOMANDA"},{r:"VENDITE",x:"ABITAZIONI"},{r:"COLLOQUIO",x:"LAVORO"},{r:"ALIMENTAZIONE",x:"GENUINA"}]},
  {id:148,w:"VISIONE",d:1,b:2,s:"NOTTURNA",c:[{r:"MONDO",x:"TERRA"},{r:"ARTIFICIALE",x:"COSTRUITA"},{r:"DOPPIA",x:"QUADRUPLA"},{r:"AZIENDALE",x:"SINTATTICA"},{r:"PERIFERICA",x:"SINISTROIDE"}]},
  {id:149,w:"SABBIA",d:1,b:1,s:"CASTELLI",c:[{r:"COSTRUIRE",x:"DEMOLIRE"},{r:"OCCHI",x:"ORECCHIE"},{r:"SCRIVERE",x:"DISEGNARE"},{r:"SEMINARE",x:"ARARE"},{r:"MARE",x:"OCEANO"}]},
  {id:150,w:"PRENDERE",d:1,b:4,s:"TEMPO",c:[{r:"LARGO",x:"STRETTO"},{r:"TORO",x:"MUCCA"},{r:"GRANCHIO",x:"GAMBERO"},{r:"LUCCIOLE",x:"FARFALLE"},{r:"LASCIARE",x:"ABBANDONARE"}]},
  {id:151,w:"FERRI",d:2,b:2,s:"MESTIERE",c:[{r:"CORTI",x:"LUNGHI"},{r:"MESTIERE",x:"LAVORO"},{r:"METTERE",x:"TOGLIERE"},{r:"SOTTO",x:"SOPRA"},{r:"INCROCIARE",x:"ANNODARE"}]},
  {id:152,w:"MUSICA",d:1,b:0,s:"CAMERA",c:[{r:"MAESTRO",x:"PROF."},{r:"METTERE",x:"LEVARE"},{r:"CAMBIARE",x:"MODIF."},{r:"ORECCHIE",x:"NASO"},{r:"SUONARE",x:"CANTARE"}]},
  {id:153,w:"VENTO",d:1,b:1,s:"ROSA",c:[{r:"BUTTARE",x:"GETTARE"},{r:"BUON",x:"BON"},{r:"SEMINARE",x:"COLTIVARE"},{r:"GRIDARE",x:"URLARE"},{r:"MANI",x:"PIEDI"}]},
  {id:154,w:"ACQUA",d:1,b:3,s:"SANTA",c:[{r:"PELO",x:"PELI"},{r:"BOCCA",x:"NASO"},{r:"ROSE",x:"GIGLI"},{r:"PONTI",x:"MURI"},{r:"MULINO",x:"GRANAIO"}]},
  {id:155,w:"LACRIME",d:1,b:4,s:"NAPOLETANE",c:[{r:"INGOIARE",x:"MANGIARE"},{r:"S. LORENZO",x:"S. ANTONIO"},{r:"AMARE",x:"DOLCI"},{r:"SANGUE",x:"SUDORE"},{r:"COCCODRILLO",x:"SERPENTE"}]},
  {id:156,w:"AMORE",d:1,b:0,s:"PLATONICO",c:[{r:"MADRE",x:"SORELLA"},{r:"PATRIA",x:"NAZIONE"},{r:"CIELO",x:"MARE"},{r:"ACCORDO",x:"PATTO"},{r:"FRUTTO",x:"FRUTTA"}]},
  {id:157,w:"FILO",d:1,b:3,s:"PERLE",c:[{r:"FARE",x:"DISFARE"},{r:"DISCORSO",x:"PAROLA"},{r:"RASOIO",x:"LAMETTA"},{r:"CAMMINARE",x:"MARCIARE"},{r:"TENERE",x:"TRATTENERE"}]},
  {id:158,w:"BANCO",d:2,b:0,s:"LAVORO",c:[{r:"TENERE",x:"TRATTENERE"},{r:"PROVA",x:"SFIDA"},{r:"SALTARE",x:"SALTELLARE"},{r:"SCALDARE",x:"RAFFREDD."},{r:"SOTTO",x:"SOPRA"}]},
  {id:159,w:"TEMPO",d:1,b:1,s:"PERSO",c:[{r:"FIGLIO",x:"FIGLIA"},{r:"AMMAZZARE",x:"UCCIDERE"},{r:"RITAGLI",x:"PEZZI"},{r:"CANI",x:"GATTI"},{r:"LADRO",x:"GUARDIA"}]},
  {id:160,w:"LIBRO",d:1,b:4,s:"TASCHE",c:[{r:"APERTO",x:"CHIUSO"},{r:"SOGNI",x:"VEGLIE"},{r:"SACRO",x:"PROFANO"},{r:"PARLARE",x:"DIRE"},{r:"SPIAGGIA",x:"MARE"}]},
  {id:161,w:"ALI",d:1,b:2,s:"ANGELO",c:[{r:"PIEDI",x:"CAVIGLIE"},{r:"BATTER",x:"COLPIR"},{r:"VENTO",x:"ARIA"},{r:"FANTASIA",x:"REALTÀ"},{r:"TARPARE",x:"LEGARE"}]},
  {id:162,w:"MORTE",d:2,b:2,s:"CERTA",c:[{r:"PAPA",x:"CARDINALE"},{r:"BIANCA",x:"NERA"},{r:"FACCIA",x:"VOLTO"},{r:"SCHERZARE",x:"GIOCARE"},{r:"LETTO",x:"GIACIGLIO"}]},
  {id:163,w:"MARCIA",d:1,b:1,s:"REALE",c:[{r:"MELA",x:"PERA"},{r:"INDIETRO",x:"AVANTI"},{r:"PASSO",x:"CAMMIN."},{r:"ROMA",x:"MILANO"},{r:"MUSICALE",x:"SONORA"}]},
  {id:164,w:"GIOCO",d:1,b:3,s:"RUOLO",c:[{r:"DOPPIO",x:"SINGOLO"},{r:"PARTI",x:"SEZIONI"},{r:"PRESTIGIO",x:"FAMA"},{r:"CANDELA",x:"CERO"},{r:"SCATOLA",x:"PACCO"}]},
  {id:165,w:"OMBRA",d:2,b:2,s:"LUCE",c:[{r:"DUBBIO",x:"CERTEZZA"},{r:"PAURA",x:"TERRORE"},{r:"VIVERE",x:"MORIRE"},{r:"PETER PAN",x:"R. HOOD"},{r:"ZONA",x:"REGIONE"}]},
  {id:166,w:"VOLO",d:1,b:2,s:"PINDARICO",c:[{r:"ANGELO",x:"DIAVOLO"},{r:"PRENDERE",x:"AFFERRARE"},{r:"CAPIRSI",x:"COMPREND."},{r:"ICARO",x:"DEDALO"},{r:"UCCELLO",x:"UCCELLACCIO"}]},
  {id:167,w:"AFFARI",d:1,b:3,s:"ESTERI",c:[{r:"CUORE",x:"FEGATO"},{r:"UOMO",x:"MASCHIO"},{r:"STATO",x:"NAZIONE"},{r:"FARE",x:"COSTRUIRE"},{r:"PROPRI",x:"ALTRUI"}]},
  {id:168,w:"INFERNO",d:1,b:2,s:"CRISTALLO",c:[{r:"MANDARE",x:"INVIARE"},{r:"PENE",x:"DOLORI"},{r:"DANTE",x:"PETRARCA"},{r:"CALDO",x:"FREDDO"},{r:"VIA",x:"VIALE"}]},
  {id:169,w:"LINGUA",d:1,b:1,s:"BATTA",c:[{r:"PELI",x:"CAPELLI"},{r:"PUNTA",x:"CAPO"},{r:"SCIOLTA",x:"LEGATA"},{r:"FUOCO",x:"FIAMME"},{r:"MADRE",x:"PADRE"}]},
  {id:170,w:"PESCE",d:1,b:4,s:"SPADA",c:[{r:"ACQUA",x:"ARIA"},{r:"BARILE",x:"BOTTE"},{r:"APRILE",x:"MAGGIO"},{r:"SANO",x:"SANTO"},{r:"BUTTARSI",x:"LANCIARSI"}]},
  {id:171,w:"SANTO",d:1,b:0,s:"VENERDÌ",c:[{r:"BARBA",x:"BAFFI"},{r:"OLIO",x:"ACETO"},{r:"STINCO",x:"TALLONE"},{r:"ESSERE",x:"TROVARSI"},{r:"PARADISO",x:"INFERNO"}]},
  {id:172,w:"FIGLIO",d:1,b:2,s:"MASCHIO",c:[{r:"ARTE",x:"MUSICA"},{r:"LATTE",x:"ACQUA"},{r:"UNICO",x:"IRRIPETIBILE"},{r:"DIO",x:"DIAVOLO"},{r:"PAPÀ",x:"PAPA"}]},
  {id:173,w:"FOGLIA",d:1,b:1,s:"TÈ",c:[{r:"ESSERE",x:"AVERE"},{r:"MANGIARE",x:"DIGIUNARE"},{r:"MUOVE",x:"MUOVERE"},{r:"VENTO",x:"ARIA"},{r:"FICO",x:"PESCO"}]},
  {id:174,w:"PALLA",d:1,b:3,s:"CANESTRO",c:[{r:"PIEDE",x:"MANO"},{r:"LARDO",x:"GRASSO"},{r:"FUCILE",x:"PISTOLA"},{r:"BALZO",x:"SALTO"},{r:"IN...",x:"NEL..."}]},
  {id:175,w:"CAMPO",d:1,b:2,s:"CALCIO",c:[{r:"MINATO",x:"BOMBARDATO"},{r:"LIBERO",x:"PRIGIONIERO"},{r:"NEUTRO",x:"ACIDO"},{r:"FUORI",x:"DENTRO"},{r:"SCENDERE",x:"CALARSI"}]},
  {id:176,w:"VELE",d:1,b:2,s:"VENTO",c:[{r:"SPIEGATE",x:"INSEGNATE"},{r:"SEGNO",x:"CICATRICE"},{r:"SCIOGLIERE",x:"ANNODARE"},{r:"AMMAINARE",x:"RITIRARE"},{r:"ALZARE",x:"ABBASSARE"}]},
  {id:177,w:"FORTE",d:1,b:3,s:"PIANO",c:[{r:"FARSI",x:"DARSI"},{r:"CAVALLO",x:"ASINO"},{r:"SANSONE",x:"SALOMONE"},{r:"QUERCIA",x:"BETULLA"},{r:"ORSO",x:"PANDA"}]},
  {id:178,w:"FUOCO",d:1,b:2,s:"ARTIFICIO",c:[{r:"APRIRE",x:"CHIUDERE"},{r:"LENTO",x:"CALMO"},{r:"GOLA",x:"TRACHEA"},{r:"PAGLIA",x:"FIENO"},{r:"SPEGNERE",x:"SOFFOCARE"}]},
  {id:179,w:"BALLO",d:1,b:1,s:"LISCIO",c:[{r:"TENERE",x:"TRATTENERE"},{r:"ESSERE",x:"ESISTERE"},{r:"TIRARE",x:"LANCIARE"},{r:"ENTRARE",x:"USCIRE"},{r:"SAN VITO",x:"SAN PIETRO"}]},
  {id:180,w:"CALCIO",d:1,b:4,s:"RIGORE",c:[{r:"OSSA",x:"MUSCOLI"},{r:"ASINO",x:"MULO"},{r:"LATTE",x:"CAFFÈ"},{r:"MONDO",x:"TERRA"},{r:"SEDERE",x:"FARE SEDERE"}]},
  {id:181,w:"CAVALLO",d:1,b:2,s:"PANTALONI",c:[{r:"TROIA",x:"ATENE"},{r:"ESSERE",x:"STARE"},{r:"RITORNO",x:"ANDATA"},{r:"BATTAGLIA",x:"GUERRIGLIA"},{r:"ACCIAIO",x:"ARGENTO"}]},
  {id:182,w:"UOVO",d:1,b:0,s:"PASQUA",c:[{r:"OGGI",x:"DOMANI"},{r:"PANIERE",x:"CESTINO"},{r:"COLOMBO",x:"VESPUCCI"},{r:"PELO",x:"CAPELLO"},{r:"GALLINA",x:"GALLO"}]},
  {id:183,w:"CAMPANA",d:1,b:1,s:"VETRO",c:[{r:"SUONARE",x:"STONARE"},{r:"ORECCHIO",x:"NASO"},{r:"VETRO",x:"CRISTALLO"},{r:"MORTO",x:"VIVO"},{r:"BARGELLO",x:"MUGELLO"}]},
  {id:184,w:"DENTI",d:1,b:3,s:"STRETTI",c:[{r:"GIUDIZIO",x:"IMPRUDENZA"},{r:"UNGHIE",x:"PELLE"},{r:"LATTE",x:"CAFFÈ"},{r:"BATTERE",x:"SBATTERE"},{r:"PANE",x:"PASTA"}]},
  {id:185,w:"PORTE",d:1,b:2,s:"APERTE",c:[{r:"ESSERE",x:"ESISTERE"},{r:"SASSI",x:"MASSI"},{r:"METTERE",x:"TOGLIERE"},{r:"NASO",x:"BOCCA"},{r:"BUSSARE",x:"PICCHIARE"}]},
  {id:186,w:"FUMO",d:1,b:0,s:"LONDRA",c:[{r:"MANDARE",x:"INVIARE"},{r:"OCCHI",x:"ORECCHIE"},{r:"ARROSTO",x:"BRASATO"},{r:"VENDERE",x:"COMPRARE"},{r:"GETTARE",x:"PRENDERE"}]},
  {id:187,w:"GATTO",d:1,b:3,s:"SORIANO",c:[{r:"AGILE",x:"VIGILE"},{r:"NERO",x:"BIANCO"},{r:"SACCO",x:"BORSA"},{r:"GIOCARE",x:"BARARE"},{r:"LAVARSI",x:"VESTIRSI"}]},
  {id:188,w:"GAMBE",d:1,b:0,s:"TAVOLO",c:[{r:"SPALLA",x:"GOMITO"},{r:"BASTONI",x:"PALI"},{r:"INCROCIARE",x:"INTRECCIARE"},{r:"TAGLIARE",x:"SEGARE"},{r:"GIACOMO",x:"ANDREA"}]},
  {id:189,w:"CASTELLO",d:1,b:1,s:"DESTINO",c:[{r:"CARTE",x:"DAMA"},{r:"SABBIA",x:"TERRA"},{r:"ARIA",x:"VENTO"},{r:"SPAGNA",x:"FRANCIA"},{r:"MENZOGNE",x:"BUGIE"}]},
  {id:190,w:"SALE",d:1,b:4,s:"CUCINA",c:[{r:"ZUCCA",x:"ZUCCHINA"},{r:"GRANO",x:"GRANELLO"},{r:"TERRA",x:"ACQUA"},{r:"CODA",x:"ZAMPA"},{r:"PEPE",x:"PEPERONCINO"}]},
  {id:191,w:"CHIAVE",d:1,b:0,s:"INGLESE",c:[{r:"VIOLINO",x:"VIOLONCELLO"},{r:"USCIRE",x:"ENTRARE"},{r:"POSIZIONE",x:"POSTO"},{r:"TROVARE",x:"SCOVARE"},{r:"CHIUDERE",x:"SERRARE"}]},
  {id:192,w:"CARTE",d:1,b:2,s:"NAPOLETANE",c:[{r:"BUONE",x:"CATTIVE"},{r:"REGOLA",x:"NORMA"},{r:"TAVOLA",x:"BANCO"},{r:"PROCESSO",x:"RITO"},{r:"IMBROGLIARE",x:"RIVELARE"}]},
];

export default GHIGLIOTTINE;
